services:
    istm-core:
        image: istm-core
        container_name: istm-core
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/core/Dockerfile
            ssh:
                - default
            args:
                - PYTHON_VERSION
                - UV_VERSION
        volumes:
            - $PWD/resources:/resources
        env_file:
            - .env
            - .secrets/.env
        privileged: true

    istm-redis:
        image: redis:${REDIS_VERSION}
        container_name: istm-redis
        network_mode: host
        volumes:
            - $PWD/resources/cache/redis:/data
