services:
    por-core:
        image: por-core
        container_name: por-core
        network_mode: host
        build:
            context: .
            dockerfile: ./docker/core/Dockerfile
            ssh:
                - default
            args:
                - PYTHON_VERSION
                - UV_VERSION
        volumes:
            - $PWD/resources:/resources
        env_file:
            - .env
            - .secrets/.env
        privileged: true

    por-redis:
        image: redis:${REDIS_VERSION}
        container_name: por-redis
        network_mode: host
        volumes:
            - $PWD/resources/cache/redis:/data
        restart: unless-stopped

    por-qdrant:
        image: qdrant/qdrant:${QDRANT_VERSION}
        container_name: por-qdrant
        network_mode: host
        volumes:
            - ./resources/db/qdrant:/qdrant/storage
        restart: unless-stopped
