services:
    por-devcontainer:
        image: por-devcontainer
        container_name: por-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
            - /run/udev:/run/udev:ro
        env_file:
            - ../.env
        privileged: true
        # This keeps the devcontainer running.
        entrypoint: ["tail", "-f", "/dev/null"]
        networks:
            - por

networks:
    por:
        name: por
        driver: bridge
