from .edges import (  # noqa
    idle_state_recorder,
    recorder_conditional,
    image_prompter_image_generator,
    audio_transcriber_language_detector,
    audio_transcriber_astrology_placements_extractor,
    language_detector_gatekeeper,
    validation_checkpoint_edges,
    validation_checkpoint_conditional,
    psychological_describer_lyrics_advisor,
    psychological_describer_nietzsche_advisor,
    psychological_describer_astrology_advisor,
    psychological_describer_satc_advisor,
    psychological_describer_ancora_advisor,
    psychological_describer_rwalsh_advisor,
    psychological_describer_pr_advisor,
    printer_edges,
)
