from .edges import (  # noqa
    idle_state_recorder,
    recorder_conditional,
    image_prompter_edges,
    image_describer_microphone_remove,
    astrology_placements_detector_astrology_advisor,
    image_prompter_image_generator,
    audio_transcriber_language_detector,
    language_detector_gatekeeper,
    gatekeeper_validation_checkpoint,
    validation_checkpoint_conditional,
    psychological_describer_lyrics_advisor,
    psychological_describer_nietzsche_advisor,
    psychological_describer_satc_advisor,
    printer_edges,
)
